const BUILD = "72217analysisswrselfhealpro";
const CACHE = `lucky-number-${BUILD}`;
const CACHE_PREFIX = "lucky-number-";
const SHELL = [
  "./index.html","./style-v72218.css","./pro-core-v72218.js","./auto-route-v2-v72218.js","./app-v72218.js","./x3-pro-v72218.js","./manifest-v72218.json","./version.json",
  "./icons/icon-192.png","./icons/icon-512.png","./icons/apple-touch-icon.png","./icons/favicon-32.png"
];
async function fetchFresh(url){return fetch(`${url}${url.includes("?")?"&":"?"}b=${BUILD}`,{cache:"no-store"});}
self.addEventListener("install",event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);for(const url of SHELL){const response=await fetchFresh(url);if(!response||!response.ok)throw new Error(`Shell install failed: ${url}`);await cache.put(url,response.clone());}await self.skipWaiting();})());});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith(CACHE_PREFIX)&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();})());});
self.addEventListener("message",event=>{if(event.data?.type==="SKIP_WAITING")self.skipWaiting();});
async function networkFirstNavigation(request){const cache=await caches.open(CACHE);try{const url=new URL(request.url);url.searchParams.set("_nav",Date.now().toString());const response=await fetch(url.toString(),{cache:"no-store",headers:{"Cache-Control":"no-cache, no-store"}});if(response&&response.ok){const text=await response.clone().text();if(text.includes(`data-app-build="${BUILD}"`)||text.includes(`data-app-build='${BUILD}'`))await cache.put("./index.html",response.clone());return response;}}catch(_){}return(await cache.match("./index.html"))||Response.error();}
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==="navigate"){event.respondWith(networkFirstNavigation(request));return;}if(url.pathname.endsWith("/version.json")){event.respondWith(fetch(`${url.pathname}?t=${Date.now()}`,{cache:"no-store",headers:{"Cache-Control":"no-cache, no-store"}}).catch(()=>caches.open(CACHE).then(c=>c.match("./version.json"))));return;}const immutable=/(?:style-v72218\.css|pro-core-v72218\.js|auto-route-v2-v72218\.js|app-v72218\.js|x3-pro-v72218\.js|manifest-v72218\.json)$/.test(url.pathname);if(immutable){event.respondWith(caches.open(CACHE).then(async cache=>{const name=url.pathname.split('/').pop();const hit=await cache.match(`./${name}`);return hit||fetch(request,{cache:"no-store"});}));return;}event.respondWith(caches.match(request).then(hit=>hit||fetch(request).then(response=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE).then(c=>c.put(request,copy)).catch(()=>{});}return response;})));});
